# Numpy
##### We will work by importing numpy in this project

In [2]:
import numpy as ph

sqrt = (0,1,4,9,16,25,36)
print(sqrt)

(0, 1, 4, 9, 16, 25, 36)


In [3]:
sqrt[3]

9

In [4]:
a = ph.arange(15).reshape(3,5)

In [5]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
